
server {
	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name lampiao.ic.unicamp.br localhost processorci.ic.unicamp.br;

	location / {
		try_files $uri $uri/ =404;
	}
	
	location /jenkins {
        proxy_pass http://localhost:8080;
        include proxy_params;
    }
	location ~ /\.ht {
		deny all;
	}

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/lampiao.ic.unicamp.br/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/lampiao.ic.unicamp.br/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = processorci.ic.unicamp.br) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80 default_server;
	listen [::]:80 default_server;

	server_name processorci.ic.unicamp.br localhost;
    return 404; # managed by Certbot
}